"""Initial schema: workspaces, customers, invoices, items, payments.

Revision ID: 0001
Revises:
Create Date: 2026-09-08

Written by hand rather than autogenerated so the tenancy constraints are
explicit and reviewable. Every tenant table carries ``workspace_id`` with an
index that leads on it, because every query in the application filters on it
first.
"""

from __future__ import annotations

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0001"
down_revision: str | None = None
branch_labels = None
depends_on = None

INVOICE_STATUS = postgresql.ENUM(
    "draft",
    "sent",
    "viewed",
    "partially_paid",
    "paid",
    "overdue",
    "disputed",
    name="invoice_status",
)
RISK_LEVEL = postgresql.ENUM("low", "medium", "high", name="risk_level")


def _timestamps() -> list[sa.Column]:
    return [
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
    ]


def upgrade() -> None:
    bind = op.get_bind()
    INVOICE_STATUS.create(bind, checkfirst=True)
    RISK_LEVEL.create(bind, checkfirst=True)
    # Already created above. Without this, create_table's own DDL for these
    # columns issues an unconditional second CREATE TYPE and fails.
    INVOICE_STATUS.create_type = False
    RISK_LEVEL.create_type = False

    op.create_table(
        "workspaces",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("name", sa.String(200), nullable=False),
        sa.Column("slug", sa.String(120), nullable=False, unique=True),
        sa.Column("plan", sa.String(40), nullable=False, server_default="starter"),
        sa.Column("currency", sa.String(3), nullable=False, server_default="USD"),
        *_timestamps(),
    )

    op.create_table(
        "customers",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column(
            "workspace_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("workspaces.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column("name", sa.String(200), nullable=False),
        sa.Column("contact_name", sa.String(200), nullable=False),
        sa.Column("email", sa.String(320), nullable=False),
        sa.Column("phone", sa.String(40)),
        sa.Column("industry", sa.String(120)),
        sa.Column("payment_terms_days", sa.Integer, nullable=False, server_default="30"),
        sa.Column("customer_since", sa.Date),
        *_timestamps(),
        sa.UniqueConstraint("workspace_id", "email", name="uq_customers_workspace_email"),
    )
    op.create_index("ix_customers_workspace_id", "customers", ["workspace_id"])
    op.create_index("ix_customers_workspace_name", "customers", ["workspace_id", "name"])

    op.create_table(
        "invoices",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column(
            "workspace_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("workspaces.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column("number", sa.String(60), nullable=False),
        sa.Column(
            "customer_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("customers.id", ondelete="RESTRICT"),
            nullable=False,
        ),
        sa.Column(
            "status",
            INVOICE_STATUS,
            nullable=False,
            server_default="draft",
        ),
        sa.Column("risk", RISK_LEVEL, nullable=False, server_default="low"),
        sa.Column("amount_cents", sa.BigInteger, nullable=False),
        sa.Column("paid_cents", sa.BigInteger, nullable=False, server_default="0"),
        sa.Column("issue_date", sa.Date, nullable=False),
        sa.Column("due_date", sa.Date, nullable=False),
        sa.Column("paid_date", sa.Date),
        sa.Column("po_number", sa.String(80)),
        sa.Column("notes", sa.Text),
        sa.Column("last_contacted_at", sa.DateTime(timezone=True)),
        *_timestamps(),
        sa.UniqueConstraint("workspace_id", "number", name="uq_invoices_workspace_number"),
        # Money cannot go backwards, and you cannot receive more than you billed.
        # Enforced in the database because the application is not the only thing
        # that will ever write to this table.
        sa.CheckConstraint("amount_cents > 0", name="ck_invoices_amount_positive"),
        sa.CheckConstraint(
            "paid_cents >= 0 AND paid_cents <= amount_cents",
            name="ck_invoices_paid_within_amount",
        ),
        sa.CheckConstraint("due_date >= issue_date", name="ck_invoices_due_after_issue"),
    )
    op.create_index("ix_invoices_workspace_id", "invoices", ["workspace_id"])
    # The dashboard query: open invoices for this workspace, oldest due first.
    op.create_index(
        "ix_invoices_workspace_status_due",
        "invoices",
        ["workspace_id", "status", "due_date"],
    )
    op.create_index(
        "ix_invoices_workspace_customer", "invoices", ["workspace_id", "customer_id"]
    )

    op.create_table(
        "invoice_items",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column(
            "workspace_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("workspaces.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column(
            "invoice_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("invoices.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column("description", sa.String(300), nullable=False),
        sa.Column("quantity", sa.Integer, nullable=False, server_default="1"),
        sa.Column("unit_price_cents", sa.BigInteger, nullable=False),
        sa.Column("amount_cents", sa.BigInteger, nullable=False),
        *_timestamps(),
        sa.CheckConstraint("quantity > 0", name="ck_invoice_items_quantity_positive"),
    )
    op.create_index("ix_invoice_items_workspace_id", "invoice_items", ["workspace_id"])
    op.create_index("ix_invoice_items_invoice_id", "invoice_items", ["invoice_id"])

    op.create_table(
        "payments",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column(
            "workspace_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("workspaces.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column(
            "invoice_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("invoices.id", ondelete="RESTRICT"),
            nullable=False,
        ),
        sa.Column(
            "customer_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("customers.id", ondelete="RESTRICT"),
            nullable=False,
        ),
        sa.Column("amount_cents", sa.BigInteger, nullable=False),
        sa.Column("method", sa.String(40), nullable=False),
        sa.Column("reference", sa.String(120)),
        sa.Column("received_at", sa.DateTime(timezone=True), nullable=False),
        *_timestamps(),
        sa.CheckConstraint("amount_cents > 0", name="ck_payments_amount_positive"),
    )
    op.create_index("ix_payments_workspace_id", "payments", ["workspace_id"])
    op.create_index(
        "ix_payments_workspace_received", "payments", ["workspace_id", "received_at"]
    )


def downgrade() -> None:
    op.drop_table("payments")
    op.drop_table("invoice_items")
    op.drop_table("invoices")
    op.drop_table("customers")
    op.drop_table("workspaces")

    bind = op.get_bind()
    RISK_LEVEL.drop(bind, checkfirst=True)
    INVOICE_STATUS.drop(bind, checkfirst=True)
